package io.github.clicksilver.exporter;

import java.lang.String;
import java.util.HashMap;

public class HoneyHunter {
  static final String[] kDecoNames = {
    "Antiblast Jewel 1",
    "Antidote Jewel 1",
    "Antipara Jewel 1",
    "Artillery Jewel 1",
    "Attack Jewel 1",
    "Blast Jewel 1",
    "Blastcoat Jewel 3",
    "Blaze Jewel 1",
    "Bolt Jewel 1",
    "Bomber Jewel 1",
    "Botany Jewel 1",
    "Brace Jewel 3",
    "Challenger Jewel 2",
    "Charger Jewel 2",
    "Crisis Jewel 1",
    "Critical Jewel 2",
    "Def Lock Jewel 1",
    "Defense Jewel 1",
    "Destroyer Jewel 2",
    "Dragon Jewel 1",
    "Dragon Res Jewel 1",
    "Dragonseal Jewel 3",
    "Drain Jewel 1",
    "Draw Jewel 2",
    "Earplug Jewel 3",
    "Elementless Jewel 2",
    "Enduring Jewel 1",
    "Enhancer Jewel 2",
    "Evasion Jewel 2",
    "Expert Jewel 1",
    "Fire Res Jewel 1",
    "Flawless Jewel 2",
    "Flight Jewel 2",
    "Footing Jewel 2",
    "Forceshot Jewel 3",
    "Fortitude Jewel 1",
    "Friendship Jewel 1",
    "Frost Jewel 1",
    "Fungiform Jewel 1",
    "Furor Jewel 2",
    "Geology Jewel 1",
    "Gobbler Jewel 1",
    "Grinder Jewel 1",
    "Handicraft Jewel 3",
    "Heavy Artillery Jewel 1",
    "Hungerless Jewel 1",
    "Ice Res Jewel 1",
    "Intimidator Jewel 1",
    "Ironwall Jewel 1",
    "Jumping Jewel 2",
    "KO Jewel 2",
    "Magazine Jewel 2",
    "Maintenance Jewel 1",
    "Medicine Jewel 1",
    "Meowster Jewel 1",
    "Miasma Jewel 1",
    "Mighty Jewel 2",
    "Mighty Bow Jewel 2",
    "Mind's Eye Jewel 2",
    "Mirewalker Jewel 1",
    "Paracoat Jewel 3",
    "Paralyzer Jewel 1",
    "Pep Jewel 1",
    "Physique Jewel 2",
    "Pierce Jewel 3",
    "Poisoncoat Jewel 3",
    "Potential Jewel 2",
    "Protection Jewel 1",
    "Recovery Jewel 1",
    "Refresh Jewel 2",
    "Release Jewel 3",
    "Resistor Jewel 1",
    "Satiated Jewel 1",
    "Scent Jewel 1",
    "Sharp Jewel 2",
    "Sheath Jewel 1",
    "Shield Jewel 2",
    "Sleep Jewel 1",
    "Sleepcoat Jewel 3",
    "Slider Jewel 2",
    "Sonorous Jewel 1",
    "Specimen Jewel 1",
    "Spread Jewel 3",
    "Sprinter Jewel 2",
    "Steadfast Jewel 1",
    "Stonethrower Jewel 1",
    "Stream Jewel 1",
    "Survival Jewel 1",
    "Suture Jewel 1",
    "Tenderizer Jewel 2",
    "Throttle Jewel 2",
    "Thunder Res Jewel 1",
    "Tip Toe Jewel 1",
    "Trueshot Jewel 1",
    "Venom Jewel 1",
    "Vitality Jewel 1",
    "Water Res Jewel 1",
    "Wind Resist Jewel 2",
    "Cooling Jewel 2",
    "Phoenix Jewel 3",
    "Guardian Jewel 2",
    "Warming Jewel 2",
    "Fire Res Jewel+ 4",
    "Water Res Jewel+ 4",
    "Ice Res Jewel+ 4",
    "Thunder Res Jewel+ 4",
    "Dragon Res Jewel+ 4",
    "Blaze Jewel+ 4",
    "Stream Jewel+ 4",
    "Frost Jewel+ 4",
    "Bolt Jewel+ 4",
    "Dragon Jewel+ 4",
    "Venom Jewel+ 4",
    "Paralyzer Jewel+ 4",
    "Sleep Jewel+ 4",
    "Blast Jewel+ 4",
    "Hard Fire Res Jewel 4",
    "Hard Water Res Jewel 4",
    "Hard Ice Res Jewel 4",
    "Hard Thunder Res Jewel 4",
    "Hard Dragon Res Jewel 4",
    "Antidote Jewel+ 4",
    "Antipara Jewel+ 4",
    "Pep Jewel+ 4",
    "Steadfast Jewel+ 4",
    "Antiblast Jewel+ 4",
    "Suture Jewel+ 4",
    "Def Lock Jewel+ 4",
    "Miasma Jewel+ 4",
    "Hungerless Jewel+ 4",
    "Recovery Jewel+ 4",
    "Tip Toe Jewel+ 4",
    "Intimidator Jewel+ 4",
    "Meowster Jewel+ 4",
    "Hard Tip Toe Jewel 4",
    "Hard Intimidator Jewel 4",
    "Hard Meowster Jewel 4",
    "Trueshot Jewel+ 4",
    "Heavy Artillery Jewel+ 4",
    "Botany Jewel+ 4",
    "Geology Jewel+ 4",
    "Survival Jewel+ 4",
    "Mirewalker Jewel+ 4",
    "Specimen Jewel+ 4",
    "Sonorous Jewel+ 4",
    "Hard Botany Jewel+ 4",
    "Hard Geology Jewel 4",
    "Hard Survival Jewel 4",
    "Hard Specimen Jewel 4",
    "Enduring Jewel+ 4",
    "Defense Jewel+ 4",
    "Hard Enduring Jewel 4",
    "Hard Defense Jewel 4",
    "Artillery Jewel+ 4",
    "Earplug Jewel+ 4",
    "Wind Resist Jewel+ 4",
    "Attack Jewel+ 4",
    "Expert Jewel+ 4",
    "Handicraft Jewel+ 4",
    "Throttle Jewel+ 4",
    "Challenger Jewel+ 4",
    "Potential Jewel+ 4",
    "Furor Jewel+ 4",
    "Physique Jewel+ 4",
    "Evasion Jewel+ 4",
    "Ironwall Jewel+ 4",
    "Friendship Jewel+ 4",
    "Drain/Physique Jewel 4",
    "Fortitude/Physique Jewel 4",
    "Crisis/Physique Jewel 4",
    "Ironwall/Physique Jewel 4",
    "Friendship/Physique Jewel 4",
    "Satiated/Physique Jewel 4",
    "Stonethrower/Physique Jewel 4",
    "Resistor/Physique Jewel 4",
    "Flight/Physique Jewel 4",
    "Sprinter/Physique Jewel 4",
    "Refresh/Physique Jewel 4",
    "Jumping/Physique Jewel 4",
    "Sheath/Physique Jewel 4",
    "Gobbler/Physique Jewel 4",
    "Grinder/Physique Jewel 4",
    "Bomber/Physique Jewel 4",
    "Fungiform/Physique Jewel 4",
    "Slider/Physique Jewel 4",
    "Guardian/Physique Jewel 4",
    "Drain/Evasion Jewel 4",
    "Fortitude/Evasion Jewel 4",
    "Crisis/Evasion Jewel 4",
    "Ironwall/Evasion Jewel 4",
    "Friendship/Evasion Jewel 4",
    "Satiated/Evasion Jewel 4",
    "Stonethrower/Evasion Jewel 4",
    "Resistor/Evasion Jewel 4",
    "Flight/Evasion Jewel 4",
    "Sprinter/Evasion Jewel 4",
    "Refresh/Evasion Jewel 4",
    "Jumping/Evasion Jewel 4",
    "Sheath/Evasion Jewel 4",
    "Gobbler/Evasion Jewel 4",
    "Grinder/Evasion Jewel 4",
    "Bomber/Evasion Jewel 4",
    "Fungiform/Evasion Jewel 4",
    "Slider/Evasion Jewel 4",
    "Guardian/Evasion Jewel 4",
    "Drain/Attack Jewel 4",
    "Fortitude/Attack Jewel 4",
    "Crisis/Attack Jewel 4",
    "Ironwall/Attack Jewel 4",
    "Friendship/Attack Jewel 4",
    "Satiated/Attack Jewel 4",
    "Stonethrower/Attack Jewel 4",
    "Resistor/Attack Jewel 4",
    "Flight/Attack Jewel 4",
    "Sprinter/Attack Jewel 4",
    "Refresh/Attack Jewel 4",
    "Jumping/Attack Jewel 4",
    "Sheath/Attack Jewel 4",
    "Gobbler/Attack Jewel 4",
    "Grinder/Attack Jewel 4",
    "Bomber/Attack Jewel 4",
    "Fungiform/Attack Jewel 4",
    "Slider/Attack Jewel 4",
    "Guardian/Attack Jewel 4",
    "Drain/Expert Jewel 4",
    "Fortitude/Expert Jewel 4",
    "Crisis/Expert Jewel 4",
    "Ironwall/Expert Jewel 4",
    "Friendship/Expert Jewel 4",
    "Satiated/Expert Jewel 4",
    "Stonethrower/Expert Jewel 4",
    "Resistor/Expert Jewel 4",
    "Flight/Expert Jewel 4",
    "Sprinter/Expert Jewel 4",
    "Refresh/Expert Jewel 4",
    "Jumping/Expert Jewel 4",
    "Sheath/Expert Jewel 4",
    "Gobbler/Expert Jewel 4",
    "Grinder/Expert Jewel 4",
    "Bomber/Expert Jewel 4",
    "Fungiform/Expert Jewel 4",
    "Slider/Expert Jewel 4",
    "Guardian/Expert Jewel 4",
    "Drain/Release Jewel 4",
    "Fortitude/Release Jewel 4",
    "Crisis/Release Jewel 4",
    "Ironwall/Release Jewel 4",
    "Friendship/Release Jewel 4",
    "Satiated/Release Jewel 4",
    "Stonethrower/Release Jewel 4",
    "Resistor/Release Jewel 4",
    "Flight/Release Jewel 4",
    "Sprinter/Release Jewel 4",
    "Refresh/Release Jewel 4",
    "Jumping/Release Jewel 4",
    "Sheath/Release Jewel 4",
    "Gobbler/Release Jewel 4",
    "Grinder/Release Jewel 4",
    "Bomber/Release Jewel 4",
    "Fungiform/Release Jewel 4",
    "Slider/Release Jewel 4",
    "Guardian/Release Jewel 4",
    "Drain/Handicraft Jewel 4",
    "Fortitude/Handicraft Jewel 4",
    "Crisis/Handicraft Jewel 4",
    "Ironwall/Handicraft Jewel 4",
    "Friendship/Handicraft Jewel 4",
    "Satiated/Handicraft Jewel 4",
    "Stonethrower/Handicraft Jewel 4",
    "Resistor/Handicraft Jewel 4",
    "Flight/Handicraft Jewel 4",
    "Sprinter/Handicraft Jewel 4",
    "Refresh/Handicraft Jewel 4",
    "Jumping/Handicraft Jewel 4",
    "Sheath/Handicraft Jewel 4",
    "Gobbler/Handicraft Jewel 4",
    "Grinder/Handicraft Jewel 4",
    "Bomber/Handicraft Jewel 4",
    "Fungiform/Handicraft Jewel 4",
    "Slider/Handicraft Jewel 4",
    "Guardian/Handicraft Jewel 4",
    "Footing/Protection Jewel 4",
    "Charger/Protection Jewel 4",
    "Enhancer/Protection Jewel 4",
    "Destroyer/Protection Jewel 4",
    "KO/Protection Jewel 4",
    "Potential/Protection Jewel 4",
    "Wind Resist/Protection Jewel 4",
    "Draw/Protection Jewel 4",
    "Throttle/Protection Jewel 4",
    "Challenger/Protection Jewel 4",
    "Flawless/Protection Jewel 4",
    "Furor/Protection Jewel 4",
    "Mighty/Protection Jewel 4",
    "Brace/Protection Jewel 4",
    "Phoenix/Protection Jewel 4",
    "Earplug/Protection Jewel 4",
    "Critical/Protection Jewel 4",
    "Tenderizer/Protection Jewel 4",
    "Handicraft/Protection Jewel 4",
    "Release/Protection Jewel 4",
    "Footing/Medicine Jewel 4",
    "Charger/Medicine Jewel 4",
    "Enhancer/Medicine Jewel 4",
    "Destroyer/Medicine Jewel 4",
    "KO/Medicine Jewel 4",
    "Potential/Medicine Jewel 4",
    "Wind Resist/Medicine Jewel 4",
    "Draw/Medicine Jewel 4",
    "Throttle/Medicine Jewel 4",
    "Challenger/Medicine Jewel 4",
    "Flawless/Medicine Jewel 4",
    "Furor/Medicine Jewel 4",
    "Mighty/Medicine Jewel 4",
    "Brace/Medicine Jewel 4",
    "Phoenix/Medicine Jewel 4",
    "Earplug/Medicine Jewel 4",
    "Critical/Medicine Jewel 4",
    "Tenderizer/Medicine Jewel 4",
    "Handicraft/Medicine Jewel 4",
    "Release/Medicine Jewel 4",
    "Footing/Vitality Jewel 4",
    "Charger/Vitality Jewel 4",
    "Enhancer/Vitality Jewel 4",
    "Destroyer/Vitality Jewel 4",
    "KO/Vitality Jewel 4",
    "Potential/Vitality Jewel 4",
    "Wind Resist/Vitality Jewel 4",
    "Draw/Vitality Jewel 4",
    "Throttle/Vitality Jewel 4",
    "Challenger/Vitality Jewel 4",
    "Flawless/Vitality Jewel 4",
    "Furor/Vitality Jewel 4",
    "Mighty/Vitality Jewel 4",
    "Brace/Vitality Jewel 4",
    "Phoenix/Vitality Jewel 4",
    "Earplug/Vitality Jewel 4",
    "Critical/Vitality Jewel 4",
    "Tenderizer/Vitality Jewel 4",
    "Handicraft/Vitality Jewel 4",
    "Release/Vitality Jewel 4",
    "Footing/Maintenance Jewel 4",
    "Charger/Maintenance Jewel 4",
    "Enhancer/Maintenance Jewel 4",
    "Destroyer/Maintenance Jewel 4",
    "KO/Maintenance Jewel 4",
    "Potential/Maintenance Jewel 4",
    "Wind Resist/Maintenance Jewel 4",
    "Draw/Maintenance Jewel 4",
    "Throttle/Maintenance Jewel 4",
    "Challenger/Maintenance Jewel 4",
    "Flawless/Maintenance Jewel 4",
    "Furor/Maintenance Jewel 4",
    "Mighty/Maintenance Jewel 4",
    "Brace/Maintenance Jewel 4",
    "Phoenix/Maintenance Jewel 4",
    "Earplug/Maintenance Jewel 4",
    "Critical/Maintenance Jewel 4",
    "Tenderizer/Maintenance Jewel 4",
    "Handicraft/Maintenance Jewel 4",
    "Release/Maintenance Jewel 4",
    "Footing/Physique Jewel 4",
    "Charger/Physique Jewel 4",
    "Enhancer/Physique Jewel 4",
    "Destroyer/Physique Jewel 4",
    "KO/Physique Jewel 4",
    "Potential/Physique Jewel 4",
    "Wind Resist/Physique Jewel 4",
    "Draw/Physique Jewel 4",
    "Throttle/Physique Jewel 4",
    "Challenger/Physique Jewel 4",
    "Flawless/Physique Jewel 4",
    "Furor/Physique Jewel 4",
    "Mighty/Physique Jewel 4",
    "Brace/Physique Jewel 4",
    "Phoenix/Physique Jewel 4",
    "Earplug/Physique Jewel 4",
    "Critical/Physique Jewel 4",
    "Tenderizer/Physique Jewel 4",
    "Handicraft/Physique Jewel 4",
    "Release/Physique Jewel 4",
    "Footing/Evasion Jewel 4",
    "Charger/Evasion Jewel 4",
    "Enhancer/Evasion Jewel 4",
    "Destroyer/Evasion Jewel 4",
    "KO/Evasion Jewel 4",
    "Potential/Evasion Jewel 4",
    "Wind Resist/Evasion Jewel 4",
    "Draw/Evasion Jewel 4",
    "Throttle/Evasion Jewel 4",
    "Challenger/Evasion Jewel 4",
    "Flawless/Evasion Jewel 4",
    "Furor/Evasion Jewel 4",
    "Mighty/Evasion Jewel 4",
    "Brace/Evasion Jewel 4",
    "Phoenix/Evasion Jewel 4",
    "Earplug/Evasion Jewel 4",
    "Critical/Evasion Jewel 4",
    "Tenderizer/Evasion Jewel 4",
    "Handicraft/Evasion Jewel 4",
    "Release/Evasion Jewel 4",
  };

  static final int kDecoMaxCounts[] = {
    3, 3, 3, 5, 7, 4, 1, 6, 6, 5, 4, 3, 7, 3, 1, 3, 3, 7, 3, 6, 3, 1, 5, 3, 5, 1, 3, 3, 5, 7, 3, 3, 1, 3, 2, 1, 5, 6, 3,
    5, 3, 3, 3, 5, 2, 3, 3, 3, 5, 3, 5, 1, 5, 3, 5, 3, 5, 1, 1, 3, 1, 4, 3, 5, 2, 1, 5, 5, 3, 3, 3, 3, 3, 1, 1, 3, 1, 4,
    1, 1, 2, 3, 2, 3, 3, 5, 6, 3, 3, 3, 7, 3, 3, 2, 4, 3, 3, 5, 1, 3, 3, 1, 5, 5, 5, 5, 5, 8, 8, 8, 8, 8, 6, 6, 6, 6, 5,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 5, 5, 7, 4, 4, 6, 5, 5, 5, 5, 4, 6, 5, 5, 5, 5, 9, 5, 9, 5, 7, 7,
    9, 9, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 5, 7, 7, 7, 7, 7, 7, 7, 5, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 5, 7,
    7, 7, 5, 7, 7, 7, 5, 7, 7, 7, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
    9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 3, 5, 5, 5, 3, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 7, 7, 7, 7, 7, 7, 7, 5, 7, 7, 7,
    5, 7, 7, 7, 5, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 5, 5, 7, 7, 5,
    5, 5, 5, 5, 7, 5, 5, 7, 5, 5, 5, 5, 5, 5, 7, 5, 5, 5, 7, 5, 5, 5, 5, 5, 7, 5, 5, 7, 5, 5, 5, 5, 5, 5, 7, 5, 5, 7, 7,
    5, 7, 5, 5, 5, 7, 5, 5, 7, 5, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 5, 7,
    7, 7, 7, 7, 7, 7, 7, 5, 7, 7, 7
  };

  static final int kNumDecos = kDecoNames.length;

  // Used to format the output string for exporting to Honey Hunter.
  static HashMap<String, Integer> kNameToOrdering;

  static HashMap<String, Integer> kNameToMaxCount;

  // Whether the above HashMaps are preloaded for quick queries.
  static boolean loaded = false;

  public static void LoadTables() {
    if (loaded) {
      return;
    }
    kNameToOrdering = new HashMap<String, Integer>();
    kNameToMaxCount = new HashMap<String, Integer>();
    for(int i=0; i<kDecoNames.length; i++) {
      kNameToOrdering.put(kDecoNames[i], i);
      kNameToMaxCount.put(kDecoNames[i], kDecoMaxCounts[i]);
    }
    loaded = true;
  }

  public static int getOrderingFromName(String name) {
    LoadTables();
    if (!kNameToMaxCount.containsKey(name)) {
      // System.out.println("Missing deco name: " + name);
      return -1;
    }
    return kNameToOrdering.get(name);
  }

  public static int getMaxCountFromName(String name) {
    LoadTables();
    if (!kNameToMaxCount.containsKey(name)) {
      // System.out.println("Missing deco name: " + name);
      return -1;
    }
    return kNameToMaxCount.get(name);
  }

}
